name: Build and Run

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      resourceGroupName:
        description: 'Azure resource group name'
        required: true
        default: 'rg-dp100-labs'
      region:
        description: 'Azure region'
        required: true
        default: 'South India'
      subscriptionId:
        description: 'Azure subscription ID'
        required: true
      fileShareName:
        description: 'Azure File Share name'
        required: true
      fileName:
        description: 'Python file name to run from the File Share'
        required: true
        default: 'github_actions_testing.py' # Name of the Python script you want to run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # Checkout the repository to access files

    - name: Log into Azure using github secret GITHUBACTION_SPN
      uses: Azure/login@v1.5.1 
      with:
        creds: ${{ secrets.GITHUBACTION_SPN }} # Azure Service Principal credentials
        enable-AzPSSession: true # Enables Azure PowerShell session

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x  # This sets the version of Python to use

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools
        pip install azure-storage-file-share  # Install SDK to interact with Azure File Share

    - name: Output Input Variables
      run: |
        echo "resourceGroupName: ${{ github.event.inputs.resourceGroupName }}"
        echo "subscriptionId: ${{ github.event.inputs.subscriptionId }}"
        echo "fileShareName: ${{ github.event.inputs.fileShareName }}"
        echo "fileName: ${{ github.event.inputs.fileName }}"

    - name: List Files for debugging
      run: tree  # This lists the files in the current directory for debugging

    - name: Locate Python file in Azure File Share and run
      run: |
        # Install the Azure SDK and authenticate
        pip install azure-storage-file-share

        # Define Azure connection details
        STORAGE_ACCOUNT_NAME="code-391ff5ac-6576-460f-ba4d-7e03433c68b6"  # Replace with your actual storage account name
        FILE_SHARE_NAME="${{ github.event.inputs.fileShareName }}"
        FILE_NAME="${{ github.event.inputs.fileName }}"

        # Ensure the Azure File Share is mounted or use the Azure SDK to download the file
    - name: Locate the File Share Directory and Ensure It Exists
      run: |
        # Set a directory in /tmp (this is writable)
        AZURE_FILE_SHARE_DIR="/tmp/azurefileshare"
        
        # Debug the value of the directory variable
        echo "Azure File Share Directory: $AZURE_FILE_SHARE_DIR"
    
        # Create the directory (mkdir -p will not fail if it exists)
        mkdir -p $AZURE_FILE_SHARE_DIR
        
                
        az storage file download --account-name $STORAGE_ACCOUNT_NAME --share-name $FILE_SHARE_NAME --path $FILE_NAME --dest $AZURE_FILE_SHARE_DIR/$FILE_NAME --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

        # Run the Python file directly from the Azure File Share
        python3 $AZURE_FILE_SHARE_DIR/$FILE_NAME
