name: Build and Run

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      resourceGroupName:
        description: 'Azure resource group name'
        required: true
        default: 'rg-dp100-labs'
      region:
        description: 'Azure region'
        required: true
        default: 'South India'
      subscriptionId:
        description: 'Azure subscription ID'
        required: true
      fileShareName:
        description: 'Azure File Share name'
        required: true
      fileName:
        description: 'Python file name to run from the File Share'
        required: true
        default: 'github_actions_testing.py' # Name of the Python script you want to run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # Checkout the repository to access files

    - name: Log into Azure using github secret GITHUBACTION_SPN
      uses: Azure/login@v1.5.1 
      with:
        creds: ${{ secrets.GITHUBACTION_SPN }} # Azure Service Principal credentials
        enable-AzPSSession: true # Enables Azure PowerShell session

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x  # This sets the version of Python to use

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools
        pip install azure-storage-file-share  # Install SDK to interact with Azure File Share

    - name: Output Input Variables
      run: |
        echo "resourceGroupName: ${{ github.event.inputs.resourceGroupName }}"
        echo "subscriptionId: ${{ github.event.inputs.subscriptionId }}"
        echo "fileShareName: ${{ github.event.inputs.fileShareName }}"
        echo "fileName: ${{ github.event.inputs.fileName }}"

    - name: List Files for debugging
      run: tree  # This lists the files in the current directory for debugging

    - name: Locate Python file in Azure File Share and run
      run: |
        # Install the Azure SDK and authenticate
        pip install azure-storage-file-share

        # Define Azure connection details
        STORAGE_ACCOUNT_NAME="code-391ff5ac-6576-460f-ba4d-7e03433c68b6"  # Replace with your actual storage account name
        FILE_SHARE_NAME="${{ github.event.inputs.fileShareName }}"
        FILE_NAME="${{ github.event.inputs.fileName }}"





    - name: Download Python File from Azure File Share and Run
      run: |
        # Set the directory path for downloaded files
        AZURE_FILE_SHARE_DIR="/tmp/azurefileshare"  # Using /tmp instead of /mnt
    
        # Debug and check if the directory is set correctly
        echo "Using Azure File Share Directory: $AZURE_FILE_SHARE_DIR"
        
        # Create the directory if it doesn't exist
        mkdir -p $AZURE_FILE_SHARE_DIR
    
        # Define the storage account and file share
        STORAGE_ACCOUNT_NAME="${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"  # Replace with your GitHub secret
        STORAGE_ACCOUNT_KEY="${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}"    # Replace with your GitHub secret
    
        # Debugging output to ensure these variables are being set correctly
        echo "Storage Account Name: $STORAGE_ACCOUNT_NAME"
        echo "Storage Account Key: $STORAGE_ACCOUNT_KEY"  # Do not print this key in production, it's only for debugging here
    
        # Download the Python file from Azure File Share to this directory
        az storage file download --account-name $STORAGE_ACCOUNT_NAME --account-key $STORAGE_ACCOUNT_KEY --share-name $FILE_SHARE_NAME --path $FILE_NAME --dest $AZURE_FILE_SHARE_DIR/$FILE_NAME
    
        # Run the downloaded Python file
        python3 $AZURE_FILE_SHARE_DIR/$FILE_NAME





  

        az storage file download --account-name $STORAGE_ACCOUNT_NAME --share-name $FILE_SHARE_NAME --path $FILE_NAME --dest $AZURE_FILE_SHARE_DIR/$FILE_NAME --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

        # Run the Python file directly from the Azure File Share
        python3 $AZURE_FILE_SHARE_DIR/$FILE_NAME
